import "@/app/globals.css";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "World In Collision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-slate-950 w-full h-screen">
            <header>
            <nav>
              <ul className="menu">
                  <li><Link href="/"> Home </Link></li>
                  <li><Link href="/notfound"> Página não encontrada </Link></li>
                  <li><Link href="/">asd </Link></li>
              </ul>
            </nav>
            </header>
        {children}
      </body>
    </html>
  );
}
