import "@/app/globals.css";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "World In Collision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho />
        {children}
      </body>
    </html>
  );
}
