import "@/app/globals.css";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "World In Collision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-slate-950 w-full h-screen">
            <header>
              <nav>
                <ul className="menu">
                    <li><Link href="/"> Home </Link></li>
                    <li><Link href="/cometa">Cometa</Link></li>
                    <li><Link href="/calculo">Calculo</Link></li>
                    <li><Link href="/catastrofe">Catastrofe</Link></li>
                </ul>
              </nav>
            </header>
        {children}
      </body>
    </html>
  );
}
